spring:
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im
    username: root
    password: bbb123=6
