mybatis-plus:
  # xml地址
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名法
    map-underscore-to-camel-case: true

# minio相关配置
oss:
  enabled: true
  type: minio
  endpoint: http://47.99.73.85:9000
  access-key: qdNFZVP3xP5ajBpG
  secret-key: 4rllwlmP54uDA9BW3EWJKfl3gSjqyU0N
  bucketName: im-bucket

# 敏感词配置
sensitive:
  enabled: true
  type: AC

# rocketmq
rocketmq:
  name-server: 47.99.73.85:9876
  access-key: admin050119
  secret-key: Cjy050119

IM:
  # mysql
  mysql:
    ip: 47.99.73.85
    port: 3306
    db: IM
    username: root
    password: Cjy050119
  # redis
  redis:
    host: 47.99.73.85
    port: 6379
    password: Cjy050119

