spring:
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im
    username: root
    password: bbb123=6

mybatis-plus:
  # xml地址
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名法
    map-underscore-to-camel-case: true
server:
  port: 8081

# minio相关配置
oss:
  enabled: true
  type: minio
  endpoint: http://localhost:9005
  access-key: GehNalA86EyHbLXEoQUk
  secret-key: PI2LUYwtAHlNspvOjMnSQ18jbEab2zieoqwVKOAj
  bucketName: test

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:
        - com.iflove.user.controller
        - com.iflove.chat.controller
        - com.iflove.video.controller
        - com.iflove.social.controller
        - com.iflove.interactive.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true